[workspace]
members = [
  "cli",
  "core",
  "test_plugin",
  "test_util",
  "op_crates/web",
]
exclude = [
  "std/hash/_wasm"
]

[profile.dev]
debug = 1

[profile.test]
debug = 1

[patch.crates-io]
rusty_v8 = { path = './rusty_v8' }
