name: ci

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.config.v8_version }}
    if: |
      github.event_name == 'push' ||
      !startsWith(github.event.pull_request.head.label, 'denoland:')
    runs-on: ubuntu-18.04
    timeout-minutes: 120
    strategy:
      matrix:
        config:
          - v8_version: 96fc9e5
          - v8_version: ee9e942
          - v8_version: 388a317
          - v8_version: 64dfb0b

      fail-fast: false

    env:
      CARGO_INCREMENTAL: 0
      RUST_BACKTRACE: full
      V8_FROM_SOURCE: 1

    steps:
      - name: Configure git
        run: |-
          git config --global core.symlinks true
          git config --global user.email "foo@bar.com"
          git config --global user.name "Foo Bar"

      - name: Clone repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 6
          submodules: true

      - name: Install rust
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: 1.45.2

      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: "2.7"
          architecture: x64

      - name: Checkout V8 version
        env:
          V8_VERSION: ${{ matrix.config.v8_version }}
        run: |-
          git submodule update --init --recursive --depth=1
          git -C rusty_v8 revert --no-edit 12334ffef12ef9126d0c47fdba35e3d4cc615f81
          git -C rusty_v8/v8 fetch --depth 10 origin 8.6.347:a 8.6.348:b
          git -C rusty_v8/v8 checkout $V8_VERSION

      - name: Build test_server
        run: cargo build -p test_util --bin test_server

      - name: Test
        run: |-
          cargo test -p deno --bin deno -vv -- --test-threads=1 --nocapture --exact worker::tests::execute_006_url_imports
          cargo test -p deno --bin deno -vv -- --test-threads=1 --nocapture --exact tsc::tests::test_compile
          cargo test -p deno --bin deno -vv -- --test-threads=1 --nocapture --exact tsc::tests::test_bundle
