name: ci

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.config.v8_version }}
    if: |
      github.event_name == 'push' ||
      !startsWith(github.event.pull_request.head.label, 'denoland:')
    runs-on: ubuntu-18.04
    timeout-minutes: 120
    strategy:
      matrix:
        config:
          - v8_version: 8.6.334
          - v8_version: 8.6.335
          - v8_version: 8.6.336
          - v8_version: 8.6.337
          - v8_version: 8.6.338
          - v8_version: 8.6.339
          - v8_version: 8.6.340
          - v8_version: 8.6.341
          - v8_version: 8.6.342
          - v8_version: 8.6.343
          - v8_version: 8.6.344
          - v8_version: 8.6.345
          - v8_version: 8.6.346
          - v8_version: 8.6.347
          - v8_version: 8.6.348
          - v8_version: 8.6.349
          - v8_version: 8.6.350
          - v8_version: 8.6.351
          - v8_version: 8.6.352
          - v8_version: 8.6.353
          - v8_version: 8.6.354
          - v8_version: 8.6.355
          - v8_version: 8.6.356
          - v8_version: 8.6.357
          - v8_version: 8.6.358
          - v8_version: 8.6.359
          - v8_version: 8.6.360
          - v8_version: 8.6.361
          - v8_version: 8.6.362
          - v8_version: 8.6.363
          - v8_version: 8.6.364
          - v8_version: 8.6.365
          - v8_version: 8.6.366
          - v8_version: 8.6.367
          - v8_version: 8.6.368
          - v8_version: 8.6.369
          - v8_version: 8.6.370
          - v8_version: 8.6.371
          - v8_version: 8.6.372
          - v8_version: 8.6.373
          - v8_version: 8.6.374
          - v8_version: 8.6.375
          - v8_version: 8.6.376
          - v8_version: 8.6.377
          - v8_version: 8.6.378
          - v8_version: 8.6.379
          - v8_version: 8.6.380
          - v8_version: 8.6.381
          - v8_version: 8.6.382
          - v8_version: 8.6.383
          - v8_version: 8.6.384
          - v8_version: 8.6.385
          - v8_version: 8.6.386
          - v8_version: 8.6.387
          - v8_version: 8.6.388
          - v8_version: 8.6.389
          - v8_version: 8.6.390
          - v8_version: 8.6.391
          - v8_version: 8.6.392
          - v8_version: 8.6.393
          - v8_version: 8.6.394
          - v8_version: 8.6.395
          - v8_version: 8.6.395.1
          - v8_version: 8.6.395.2
          - v8_version: 8.6.395.3
          - v8_version: 8.6.396
          - v8_version: 8.6.397
          - v8_version: 8.6.398
          - v8_version: 8.6.399
          - v8_version: 8.6.400
          - v8_version: 8.6.401
          - v8_version: 8.6.402
          - v8_version: 8.6.403
          - v8_version: 8.6.404
          - v8_version: 8.6.405
          - v8_version: 8.7.1
          - v8_version: 8.7.2
          - v8_version: 8.7.3
          - v8_version: 8.7.4
          - v8_version: 8.7.5
          - v8_version: 8.7.6
          - v8_version: 8.7.7
          - v8_version: 8.7.8
          - v8_version: 8.7.9
          - v8_version: 8.7.10
          - v8_version: 8.7.11
          - v8_version: 8.7.12
          - v8_version: 8.7.13
          - v8_version: 8.7.14
          - v8_version: 8.7.15
          - v8_version: 8.7.16
          - v8_version: 8.7.17
          - v8_version: 8.7.18
          - v8_version: 8.7.19
          - v8_version: 8.7.20
          - v8_version: 8.7.21
          - v8_version: 8.7.22
          - v8_version: 8.7.23
          - v8_version: 8.7.24
          - v8_version: 8.7.25
          - v8_version: 8.7.26

      fail-fast: false

    env:
      CARGO_INCREMENTAL: 0
      RUST_BACKTRACE: full
      V8_FROM_SOURCE: 1

    steps:
      - name: Configure git
        run: |-
          git config --global core.symlinks true
          git config --global user.email "foo@bar.com"
          git config --global user.name "Foo Bar"

      - name: Clone repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 6
          submodules: true

      - name: Install rust
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: 1.45.2

      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: "2.7"
          architecture: x64

      - name: Checkout V8 version
        env:
          V8_VERSION: ${{ matrix.config.v8_version }}
        run: |-
          git submodule update --init --recursive --depth=1
          git -C rusty_v8 revert --no-edit 12334ffef12ef9126d0c47fdba35e3d4cc615f81
          git -C rusty_v8/v8 fetch --depth=1 origin refs/tags/$V8_VERSION
          git -C rusty_v8/v8 checkout FETCH_HEAD

      - name: Build test_server
        run: cargo build -p test_util --bin test_server

      - name: Test
        run: |-
          cargo test -p deno --bin deno -vv -- --test-threads=1 --nocapture --exact worker::tests::execute_006_url_imports
          cargo test -p deno --bin deno -vv -- --test-threads=1 --nocapture --exact tsc::tests::test_compile
          cargo test -p deno --bin deno -vv -- --test-threads=1 --nocapture --exact tsc::tests::test_bundle
